### ISSUE TITLE
铲子道具有BUG

### ISSUE THREAD

**Issue by HexRune** [xiongfj/FC-Tank#2]
大佬你好，我是一个C++初学者，下载了您的代码学习，在运行后发现了两个BUG：
1.铲子道具只有第一次拾取才有效果，后面不管拾取多少次大本营都不会切换到铁墙模式；
2.拾取铲子道具后大本营会一直维持在铁墙状态，不会随着时间变化切换会普通砖墙；

我试着修改了 PlayerBase.cpp 中的 DispatchProp(int prop_kind) 函数的代码，大概位置在 777行 ：
`void PlayerBase::DispatchProp(int prop_kind)
{
	MciSound::_PlaySound(S_GETPROP);
	mProp.StopShowProp(true);

	switch (prop_kind)
	{
	...
	case SHOVEL_PROP:		// 铲子
		mShovelProp = true;
		mShovelProp_counter = 0;    // 新增代码
		break;
	...
	default:
		break;
	}
}`

目前解决了铲子只能拾取一次的BUG；
大本营无法切换回普通砖块状态的问题还没解决，正在研究；

**Comment by xiongfj** [comment]
感谢提交~     大本营无法切换砖头的 bug 也已经修复
