### ISSUE TITLE
地图数据错误

### ISSUE THREAD

**Issue by HandsomeGiao** [xiongfj/FC-Tank#4]
map_12只有22行数据，缺少4行。

**Comment by HandsomeGiao** [comment]
map_16缺少一行数据，其余都正确。

**Comment by HandsomeGiao** [comment]
map_16少了一行数据，，另外还有两行分别少了一个字符，但我忘了，可以用正则表达式查一下。

**Comment by xiongfj** [comment]
> map_16少了一行数据，，另外还有两行分别少了一个字符，但我忘了，可以用正则表达式查一下。

感谢反馈，已更正
